import './globals.css'
import { Open_Sans as OpenSans } from 'next/font/google'
import Footer from '@/components/Footer'

const openSans = OpenSans({
  subsets: ['latin'],
  variable: '--font-openSans',
})

export const metadata = {
  title: 'alura-cases-divulgacao',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pt-BR">
      <body className={`${openSans.variable} bg-slate-100 font-sans`}>
        {children}
        <Footer />
      </body>
    </html>
  )
}
